openapi: 3.1.0
info:
  contact:
    email: bojan@distopik.com
    name: Bojan Šernek
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Audio Cloud Instance Driver
  version: 0.1.0
paths:
  /v1/instances:
    get:
      deprecated: false
      description: |
        List running instances

        List instances running on this driver enddpoint.
      operationId: list_instances
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceWithStatusList'
          description: Success
      summary: List running instances
      tags:
      - driver
  /v1/instances/{manufacturer}/{name}/{instance}/parameters:
    patch:
      deprecated: false
      description: |
        Set parameters

        Update instance parameter values.
      operationId: set_parameters
      parameters:
      - deprecated: false
        description: Model manufacturer
        in: path
        name: manufacturer
        required: true
        schema:
          type: string
      - deprecated: false
        description: Model product name
        in: path
        name: name
        required: true
        schema:
          type: string
      - deprecated: false
        description: Unique instance identifier
        in: path
        name: instance
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetInstanceParameters'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceParametersUpdated'
          description: Success
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceDriverError'
          description: Not found
      summary: Set parameters
      tags:
      - instance
  /v1/instances/{manufacturer}/{name}/{instance}/play_state:
    put:
      deprecated: false
      description: |
        Set the desired play state.

        Update desired play state of the instance.
      parameters:
      - deprecated: false
        description: Model manufacturer
        in: path
        name: manufacturer
        required: true
        schema:
          type: string
      - deprecated: false
        description: Model product name
        in: path
        name: name
        required: true
        schema:
          type: string
      - deprecated: false
        description: Unique instance identifier
        in: path
        name: instance
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DesiredInstancePlayState'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceParametersUpdated'
          description: Success
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceDriverError'
          description: Not found
      summary: Set parameters
      tags:
      - instance
servers:
- description: Local development
  url: http://localhost:7400
components:
  schemas:
    DesiredInstancePlayState:
      title: DesiredInstancePlayState
      oneOf:
      - type: object
        required:
        - playing
        properties:
          playing:
            type: object
            required:
            - play_id
            properties:
              play_id:
                $ref: '#/components/schemas/PlayId'
        additionalProperties: false
      - type: object
        required:
        - rendering
        properties:
          rendering:
            type: object
            required:
            - length
            - render_id
            properties:
              length:
                type: number
                format: double
              render_id:
                $ref: '#/components/schemas/RenderId'
        additionalProperties: false
      - type: object
        required:
        - stopped
        properties:
          stopped:
            type: object
            properties:
              position:
                type:
                - number
                - 'null'
                format: double
        additionalProperties: false
    FixedInstanceId:
      type: string
    InstanceDriverCommand:
      title: InstanceDriverCommand
      description: A command that can be sent to the instance driver
      oneOf:
      - type: string
        enum:
        - check_connection
        - stop
      - type: object
        required:
        - play
        properties:
          play:
            type: object
            required:
            - play_id
            properties:
              play_id:
                $ref: '#/components/schemas/PlayId'
        additionalProperties: false
      - type: object
        required:
        - render
        properties:
          render:
            type: object
            required:
            - length
            - render_id
            properties:
              length:
                type: number
                format: double
              render_id:
                $ref: '#/components/schemas/RenderId'
        additionalProperties: false
      - type: object
        required:
        - rewind
        properties:
          rewind:
            type: object
            required:
            - to
            properties:
              to:
                type: number
                format: double
        additionalProperties: false
      - type: object
        required:
        - set_parameters
        properties:
          set_parameters: true
        additionalProperties: false
      - type: object
        required:
        - set_power_channel
        properties:
          set_power_channel:
            type: object
            required:
            - channel
            - power
            properties:
              channel:
                type: integer
                format: uint
                minimum: 0.0
              power:
                type: boolean
        additionalProperties: false
    InstanceDriverError:
      title: InstanceDriverError
      oneOf:
      - type: string
        enum:
        - media_not_present
        - not_power_controller
        - not_interruptable
      - type: object
        required:
        - instance_not_found
        properties:
          instance_not_found:
            type: object
            required:
            - instance
            properties:
              instance:
                $ref: '#/components/schemas/FixedInstanceId'
        additionalProperties: false
      - type: object
        required:
        - parameter_does_not_exist
        properties:
          parameter_does_not_exist:
            type: object
            required:
            - error
            properties:
              error:
                type: string
        additionalProperties: false
      - type: object
        required:
        - parameters_malformed
        properties:
          parameters_malformed:
            type: object
            required:
            - error
            properties:
              error:
                type: string
        additionalProperties: false
      - type: object
        required:
        - reports_malformed
        properties:
          reports_malformed:
            type: object
            required:
            - error
            properties:
              error:
                type: string
        additionalProperties: false
      - type: object
        required:
        - config_malformed
        properties:
          config_malformed:
            type: object
            required:
            - error
            properties:
              error:
                type: string
        additionalProperties: false
      - type: object
        required:
        - i_o_error
        properties:
          i_o_error:
            type: object
            required:
            - error
            properties:
              error:
                type: string
        additionalProperties: false
      - type: object
        required:
        - driver_not_supported
        properties:
          driver_not_supported:
            type: object
            required:
            - manufacturer
            - name
            properties:
              manufacturer:
                type: string
              name:
                type: string
        additionalProperties: false
      - type: object
        required:
        - r_p_c
        properties:
          r_p_c:
            type: object
            required:
            - error
            properties:
              error:
                type: string
        additionalProperties: false
    InstanceParametersUpdated:
      title: InstanceParametersUpdated
      oneOf:
      - type: object
        required:
        - updated
        properties:
          updated:
            type: object
            required:
            - id
            - parameters
            properties:
              id:
                $ref: '#/components/schemas/FixedInstanceId'
              parameters: true
        additionalProperties: false
    InstancePlayState:
      oneOf:
      - type: string
        enum:
        - stopping
      - type: object
        required:
        - preparing_to_play
        properties:
          preparing_to_play:
            type: object
            required:
            - play_id
            properties:
              play_id:
                $ref: '#/components/schemas/PlayId'
        additionalProperties: false
      - type: object
        required:
        - playing
        properties:
          playing:
            type: object
            required:
            - play_id
            properties:
              play_id:
                $ref: '#/components/schemas/PlayId'
        additionalProperties: false
      - type: object
        required:
        - preparing_to_render
        properties:
          preparing_to_render:
            type: object
            required:
            - length
            - render_id
            properties:
              length:
                type: number
                format: double
              render_id:
                $ref: '#/components/schemas/RenderId'
        additionalProperties: false
      - type: object
        required:
        - rendering
        properties:
          rendering:
            type: object
            required:
            - length
            - render_id
            properties:
              length:
                type: number
                format: double
              render_id:
                $ref: '#/components/schemas/RenderId'
        additionalProperties: false
      - type: object
        required:
        - rewinding
        properties:
          rewinding:
            type: object
            required:
            - to
            properties:
              to:
                type: number
                format: double
        additionalProperties: false
      - type: object
        required:
        - stopped
        properties:
          stopped:
            type: object
            properties:
              position:
                type:
                - number
                - 'null'
                format: double
        additionalProperties: false
    InstanceWithStatus:
      type: object
      required:
      - actual_play_state
      - desired_play_state
      - id
      - parameters
      - reports
      properties:
        actual_play_state:
          $ref: '#/components/schemas/Timestamped_for_Nullable_InstancePlayState'
        desired_play_state:
          $ref: '#/components/schemas/Timestamped_for_Nullable_DesiredInstancePlayState'
        id:
          $ref: '#/components/schemas/FixedInstanceId'
        parameters: true
        reports:
          type: object
          additionalProperties: true
    InstanceWithStatusList:
      title: Array_of_InstanceWithStatus
      type: array
      items:
        $ref: '#/components/schemas/InstanceWithStatus'
    PlayId:
      type: string
    RenderId:
      type: string
    SetInstanceParameters:
      title: SetInstanceParameters
      type: object
      required:
      - parameters
      properties:
        parameters: true
    Timestamped_for_Nullable_DesiredInstancePlayState:
      type: array
      items:
      - type: string
        format: date-time
      - anyOf:
        - $ref: '#/components/schemas/DesiredInstancePlayState'
        - type: 'null'
      maxItems: 2
      minItems: 2
    Timestamped_for_Nullable_InstancePlayState:
      type: array
      items:
      - type: string
        format: date-time
      - anyOf:
        - $ref: '#/components/schemas/InstancePlayState'
        - type: 'null'
      maxItems: 2
      minItems: 2
