host: better-pi
#power:
#  powerController: ppdu_r1_up_l
#  driverNeedsPower: true
#  powerOn:
#    parameter: power
#    channel: 2
#    value: 1
#  powerOff:
#    parameter: power
#    channel: 2
#    value: 0
#  warmUpMs: 1000
#  coolDownMs: 2000
#  idleMs: 300000
model:
  parameters:
    linkPairs: &toggle
      range:
        type: toggle
      channels: 1
    inputLevel: &attenuation
      range:
        type: bounded
        min: -60
        max: 0
      unit: dB
      default: -24
    outputLevel: *attenuation
    release: &timing
      range:
        type: bounded
        min: 1
        max: 7
      unit: ms
    attack: *timing
    gainReductionDisable: *toggle
    ratio: 
      range:
        type: list
        values: &ratioList [ 4, 8, 12, 20 ]
      unit: n/a

  reports:
    gainReduction:
      unit: dB
      range:
        type: bounded
        min: -20
        max: 3
    volume:
      unit: dB
      range:
        type: bounded
        min: -20
        max: 3
######################################
driver:
  type: USBHID
  vendorId: 1155
  productId: 22354
  serial_number: '205F305E5656'
  pageMask: 0xF
  parameterPages:
    - page: 0
      size: 64
      header: [ 0x80, 0x00 ]
  reportPages:
    - page: 0
      size: 64

  parameters:
    linkPairs:
      - position:
          bit: [ 4, 0 ]
    inputLevel:
      - position:
          bitRange:
            - [ 6, 7 ]
            - [ 20, 21 ]
        rescale: [ [ -60, 0 ], [ 0, 0x3f ] ]
        packing: uint16be
    outputLevel:
      - position:
          bitRange:
            - [ 8, 9 ]
            - [ 18, 19 ]
        rescale: [ [ -60, 0 ], [ 0, 0x3f ] ]
        packing: uint16be
    release:
      - position:
          bitRange:
            - [ 10, 11 ]
            - [ 24, 25 ]
        rescale: [ [ 1, 7 ], [ 0, 0x3f ] ]
        packing: uint16be
    attack:
      - position:
          bitRange:
            - [ 8, 9 ]
            - [ 18, 19 ]
        rescale: [ [ 1, 7 ], [ 0, 0x3f ] ]
        packing: uint16be

    evenColorFrequency:
      - position:
          byte: 24
        remap:
          type: linear
          values: *frequencies

  reports:
    gainReduction:
      - page: 1
        packing: uint16le
        position:
          bytes: [ 1, 2 ]
        transform: gainFactorToDb(value / 1024)
      - page: 1
        packing: uint16le
        position:
          bytes: [ 3, 4 ]
        transform: gainFactorToDb(value / 1024)
    clip:
      - page: 1
        position:
          byte: 5
      - page: 1
        position:
          byte: 6
    peakLevel:
      - page: 1
        packing: int16be
        position:
          bytes: [ 7, 8 ]
        transform: Math.max(-36, value * 0.1)
      - page: 1
        packing: int16be
        position:
          bytes: [ 9, 10 ]
        transform: Math.max(-36, value * 0.1)
    rmsLevel:
      - page: 1
        packing: int16be
        position:
          bytes: [ 15, 16 ]
        transform: Math.max(-36, value * 0.1)
      - page: 1
        packing: int16be
        position:
          bytes: [ 17, 18 ]
        transform: Math.max(-36, value * 0.1)