id: btmkr_ml_1
hostId: better_pi
power:
  powerController: ppdu_r1_up_l
  powerOn:
    parameter: power
    channel: 3
    value: 1
  powerOff:
    parameter: power
    channel: 3
    value: 0
  warmUpMs: 1000
  coolDownMs: 2000
  idleMs: 300000
model:
  parameters:
    inputLevel:
      min: 0
      max: 20
      unit: dB
      channels: 1
    outputLevel:
      min: -15
      max: 5
      unit: dB
      channels: 1
    attack:
      min: 1
      max: 2500
      unit: ms
      channels: 1
    release:
      min: 10
      max: 1300
      unit: ms
      channels: 1
    clippiterAmount:
      min: 0
      max: 100
      unit: %
      channels: 1
    midSideWidth:
      min: 0
      max: 100
      unit: %
      channels: 1
    evenColorEnabled:
      step: 1
      channels: 1
    evenColorDrive:
      min: 0
      max: 100
      unit: %
      channels: 1
    evenColorAmount:
      min: 0
      max: 100
      unit: %
      channels: 1
    evenColorFrequency:
      unit: hz
      channels: 1
      min: 0
      max: 23000
      allowedValues: [ 0, 35, 45, 56, 67, 83, 100, 130, 160, 200, 300, 440, 560, 700, 900, 1050, 1250, 1500, 2000, 3000, 4000, 5000, 6000, 7000, 8500, 10000, 11500, 13500, 15000, 17000, 19000, 21000, 23000 ]
    oddColorEnabled:
      step: 1
      channels: 1
    oddColorDrive:
      min: 0
      max: 100
      unit: %
      channels: 1
    oddColorAmount:
      min: 0
      max: 100
      unit: %
      channels: 1
    oddColorFrequency:
      unit: hz
      channels: 1
      min: 0
      max: 23000
      allowedValues: [ 0, 35, 45, 56, 67, 83, 100, 130, 160, 200, 300, 440, 560, 700, 900, 1050, 1250, 1500, 2000, 3000, 4000, 5000, 6000, 7000, 8500, 10000, 11500, 13500, 15000, 17000, 19000, 21000, 23000 ]
    measureOutput:
      channels: 1
      step: 1
    processingEnabled:
      channels: 1
      step: 1
    clippiterEnabled:
      channels: 1
      step: 1
    intelligentReleaseEnabled:
      channels: 1
      step: 1
    midSideEnabled:
      channels: 1
      step: 1
  reports:
    gainReduction:
      unit: dB
      min: -20
      max: 0
    clip:
      step: 1
    peakLevel:
      unit: dB
      min: -20
      max: 10
    rmsLevel:
      unit: dB
      min: -20
      max: 10
driver:
  type: USBHID
  vendorId: 0x4D8
  productId: 0xF034
  pageMask: 0xF
  parameterPages:
    - page: 0
      size: 64
      copyFromReportPage: 0
      header: [ 0x80, 0x00 ]
  reportPages:
    - page: 0
      size: 64
    - page: 1
      size: 64
  parameters:
    inputLevel:
      - position:
          byte: 11
        rescale: [ [ 0, 20 ], [ 0, 200 ] ]
    outputLevel:
      - position:
          byte: 12
        rescale: [ [ -15, 5 ], [ 0, 200 ] ]
    attack:
      - position:
          bytes: [ 13, 14 ]
        rescale: [ [ 0, 2500 ], [ 0, 25000 ] ]
        clamp:
          min: 0
          max: 25000
        packing: uint16be
    release:
      - position:
          bytes: [ 15, 16 ]
        clamp:
          min: 10
          max: 1300
        packing: uint16be
    clippiterAmount:
      - position:
          byte: 17
        rescale: [ [ 0, 100 ], [ 0, 0xff ] ]
        clamp:
          max: 0xff
    midSideWidth:
      - position:
          byte: 18
        rescale: [ [ 0, 100 ], [ 0, 0xff ] ]
        clamp:
          max: 0xff
    evenColorEnabled:
      - position:
          bit: [ 40, 2 ]
    evenColorDrive:
      - position:
          byte: 22
        rescale: [ [ 0, 100 ], [ 1, 21 ] ]
    evenColorAmount:
      - position:
          byte: 23
        rescale: [ [ 0, 100 ], [ 1, 21 ] ]
    evenColorFrequency:
      - position:
          byte: 24
        remap:
          type: linear
          values: [ 0, 35, 45, 56, 67, 83, 100, 130, 160, 200, 300, 440, 560, 700, 900, 1050, 1250, 1500, 2000, 3000, 4000, 5000, 6000, 7000, 8500, 10000, 11500, 13500, 15000, 17000, 19000, 21000, 23000 ]
    oddColorEnabled:
      - position:
          bit: [ 40, 3 ]
    oddColorDrive:
      - position:
          byte: 19
        rescale: [ [ 0, 100 ], [ 1, 21 ] ]
    oddColorAmount:
      - position:
          byte: 20
        rescale: [ [ 0, 100 ], [ 1, 21 ] ]
    oddColorFrequency:
      - position:
          byte: 21
        remap:
          type: linear
          values: [ 0, 35, 45, 56, 67, 83, 100, 130, 160, 200, 300, 440, 560, 700, 900, 1050, 1250, 1500, 2000, 3000, 4000, 5000, 6000, 7000, 8500, 10000, 11500, 13500, 15000, 17000, 19000, 21000, 23000 ]
    measureOutput:
      - position:
          bit: [ 41, 6 ]
    processingEnabled:
      - position:
          bit: [ 40, 7 ]
    clippiterEnabled:
      - position:
          bit: [ 40, 6 ]
    intelligentReleaseEnabled:
      - position:
          bit: [ 40, 4 ]
    midSideEnabled:
      - position:
          bit: [ 40, 5 ]
  reports:
    gainReduction:
      - page: 1
        packing: uint16le
        position:
          bytes: [ 1, 2 ]
        transform: gainFactorToDb(value / 1024)
      - page: 1
        packing: uint16le
        position:
          bytes: [ 3, 4 ]
        transform: gainFactorToDb(value / 1024)
    clip:
      - page: 1
        position:
          byte: 5
      - page: 1
        position:
          byte: 6
    peakLevel:
      - page: 1
        packing: int16be
        position:
          bytes: [ 7, 8 ]
        transform: Math.max(-36, value * 0.1)
      - page: 1
        packing: int16be
        position:
          bytes: [ 9, 10 ]
        transform: Math.max(-36, value * 0.1)
    rmsLevel:
      - page: 1
        packing: int16be
        position:
          bytes: [ 15, 16 ]
        transform: Math.max(-36, value * 0.1)
      - page: 1
        packing: int16be
        position:
          bytes: [ 17, 18 ]
        transform: Math.max(-36, value * 0.1)