host: macmini
model:
  parameters:
    power:
      min: 0
      max: 1
      step: 1
      channels: 4
driver:
  type: HTTP
  baseUrl: http://10.1.254.236
  parameters:
    power:
      url: |
        `${baseUrl}/netio.json`
      body: |
        JSON.toString({
            "Outputs": [
                {
                    "ID": channel,
                    "Action": value.toFixed()
                }
            ]
        })
      headers:
        Content-Type: application/json