type: serial
serial_number: 066CFF565257867767192848
line_handler: |
  if (value.startsWith('RGST')) {
      const [transportFlags, position] = value.substring(4).split(' ').map(parseInt);
      setPosition(position);
  } else if (value.startsWith('RGSM')) {
      switch (parseInt(value.substring(4))) {
          case 0:
              setState('stopped');
              break;
          case 1:
              setState('stopping');
              break;
          case 2:
          case 3:
              setState('playing');
              break;
          case 22:
          case 23:
              setState('busy');
              break;
          default:
              setState('rewinding');
              break;
      }
  }
  return null
request_timers:
  - interval_ms: 500
    line: RGST 0000
  - interval_ms: 500
    line: RGSM 0000
parameters:
  playState:
