/*
 * Copyright (c) Audio Cloud, 2022. This code is licensed under MIT license (see LICENSE for details)
 */

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::audio_engine::CompressedAudio;
use crate::common::media::{PlayId, RenderId};
use crate::{AppTaskId, DynamicInstanceNodeId, NodePadId, PadMetering};

/// Event emitted by the audio engine
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum EngineEvent {
    /// The task has stopped
    Stopped {
        /// Task id
        task_id: AppTaskId,
    },
    /// The task is playing
    Playing {
        /// Task id
        task_id:         AppTaskId,
        /// Play id
        play_id:         PlayId,
        /// Compressed and encoded audio
        audio:           CompressedAudio,
        /// Peak meters for each source pad
        peak_metering:   HashMap<NodePadId, PadMetering>,
        /// Reports generated by dynamic instance nodes
        dynamic_reports: HashMap<DynamicInstanceNodeId, serde_json::Value>,
    },
    /// Playing failed with an error
    PlayingFailed {
        /// Task id
        task_id: AppTaskId,
        /// Play id
        play_id: PlayId,
        /// Error details
        error:   String,
    },
    /// Task is rendering
    Rendering {
        /// Taks id
        task_id:    AppTaskId,
        /// Render id
        render_id:  RenderId,
        /// Completion in percent
        completion: f64,
    },
    /// Rendering successfully finished
    RenderingFinished {
        /// Task id
        task_id:   AppTaskId,
        /// Render id
        render_id: RenderId,
        /// Path to the media file on the audio engine computer
        path:      String,
    },
    /// Rendering failed with an error
    RenderingFailed {
        /// Task id
        task_id:   AppTaskId,
        /// Render id
        render_id: RenderId,
        /// Error details
        error:     String,
    },
    /// A general error has happened on at task
    Error {
        /// Task id
        task_id: AppTaskId,
        /// Error details
        error:   String,
    },
}

impl EngineEvent {
    pub fn task_id(&self) -> &AppTaskId {
        match self {
            EngineEvent::Stopped { task_id } => task_id,
            EngineEvent::Playing { task_id, .. } => task_id,
            EngineEvent::PlayingFailed { task_id, .. } => task_id,
            EngineEvent::Rendering { task_id, .. } => task_id,
            EngineEvent::RenderingFinished { task_id, .. } => task_id,
            EngineEvent::RenderingFailed { task_id, .. } => task_id,
            EngineEvent::Error { task_id, .. } => task_id,
        }
    }
}
