// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added or an existing one is changed
    println!("cargo:rerun-if-changed=src/db/migrations");
}
