[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
derive_more = "0.99"

[dependencies.schemars]
version = "0.8"
features = ["chrono"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"]