name: Test Instance Driver Build
on:
  push: { }
jobs:
  instance_driver_arm7:
    name: armv7-unknown-linux-gnueabihf Instance Driver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: armv7-unknown-linux-gnueabihf-driver-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            armv7-unknown-linux-gnueabihf-driver-${{ env.cache-name }}-
            armv7-unknown-linux-gnueabihf-driver-
      - name: Install Linux cross compiler
        run: |
          sudo apt-get install -y gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf
      - name: Install Linux cross compiling deps
        uses: ryankurte/action-apt@v0.3.0
        with:
          arch: armhf
          packages: "libssl-dev:armhf libusb-1.0-0-dev:armhf"
      - name: Install rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup target add armv7-unknown-linux-gnueabihf
      - name: Build Driver
        run: |
          cargo build --release --target=armv7-unknown-linux-gnueabihf -p audiocloud-driver
        env:
          SYSROOT: /usr/arm-linux-gnueabihf
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_LIBDIR: /usr/lib/arm-linux-gnueabihf/pkgconfig
          PKG_CONFIG_SYSROOT_DIR: /usr/arm-linux-gnueabihf
          PKG_CONFIG_SYSTEM_LIBRARY_PATH: /usr/lib/arm-linux-gnueabihf
          PKG_CONFIG_SYSTEM_INCLUDE_PATH: /usr/arm-linux-gnueabihf/include
