name: Test Instance Driver Build
on:
  push: { }
jobs:
  instance_driver_arm7:
    name: armv7-unknown-linux-gnueabihf Instance Driver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: armv7-unknown-linux-gnueabihf-driver-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            armv7-unknown-linux-gnueabihf-driver-${{ env.cache-name }}-
            armv7-unknown-linux-gnueabihf-driver-
      - uses: actions-rs/cargo@v1
        name: Build Driver
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf --manifest-path ./domain/audiocloud-driver/Cargo.toml
        env:
          CROSS_CONFIG: ./domain/audiocloud-driver/Cross.toml