name: Run Domain Unit Tests on PRs and pushes to main
on:
  pull_request:
    branches: [ main ]
    paths:
      - "domain/audiocloud-domain-server/**"
      - "specs/audiocloud-api/**"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2
      - name: Install deps
        run: |
          sudo apt-get install -y libusb-1.0-0-dev libsasl2-dev protobuf-compiler
      - name: Run tests
        run: |
          cargo test -p audiocloud-domain-server