on:
  push:
    branches:
      - '**'
jobs:
  test_domain_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Linux Deps
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq build-essential pkg-config cmake qemu-user-static libasound2-dev libcurl4-openssl-dev libudev-dev libusb-dev
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-x86_64-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-x86_64-cargo-
      - name: Execute test
        run: |
          cargo test